"""Draw the frothedboard app icon.

Deliberately not generated by an image model: a tray icon has to survive being squeezed to 16x16,
where anything with texture or fine detail turns to mush. This is three flat rounded cards in a
stack with the front one amber — the same shape language as the banner, and still legible as a
silhouette at the smallest size Windows will ask for.

    python3 docs/make-icon.py src/Frothedboard.App/frothedboard.ico
"""

import sys

from PIL import Image, ImageDraw

SS = 4          # supersample; the master is drawn big and reduced once
MASTER = 256
SIZES = [16, 24, 32, 48, 64, 128, 256]

AMBER = (237, 155, 64, 255)
SLATE_MID = (86, 96, 103, 255)
SLATE_DARK = (58, 66, 71, 255)
ON_AMBER = (120, 70, 12, 255)


def draw(px):
    im = Image.new("RGBA", (px * SS, px * SS), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    s = px * SS / 256.0  # everything below is authored against a 256 grid

    def card(x, y, w, h, fill):
        d.rounded_rectangle((x * s, y * s, (x + w) * s, (y + h) * s), radius=26 * s, fill=fill)

    # Back to front, offset down-left, so the stack reads even when tiny.
    card(78, 20, 150, 172, SLATE_DARK)
    card(54, 42, 150, 172, SLATE_MID)
    card(28, 64, 150, 172, AMBER)

    # Three bars on the front card. They vanish into a texture by 16px, which is fine —
    # by then the amber silhouette is doing the work.
    for i, frac in enumerate((0.72, 0.52, 0.62)):
        y = 108 + i * 34
        d.rounded_rectangle((56 * s, y * s, (56 + 94 * frac) * s, (y + 16) * s),
                            radius=8 * s, fill=ON_AMBER)

    return im.resize((px, px), Image.LANCZOS)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "frothedboard.ico"
    master = draw(MASTER)
    master.save(out, format="ICO", sizes=[(n, n) for n in SIZES])
    print(f"wrote {out} with sizes {SIZES}")

    preview = sys.argv[2] if len(sys.argv) > 2 else None
    if preview:
        strip = Image.new("RGBA", (sum(SIZES) + 16 * len(SIZES), MASTER + 20), (36, 40, 43, 255))
        x = 8
        for n in SIZES:
            strip.paste(draw(n), (x, 10 + (MASTER - n) // 2), draw(n))
            x += n + 16
        strip.save(preview)
        print(f"wrote {preview}")


if __name__ == "__main__":
    main()
